# pragma once

#include "../../App/resource.h"

#include <map>
#include <vector>
#include <string>

inline std::map<int, std::vector<std::string>> canonicalAudioFileNames = {
	{ IDR_WAVE1, { "EP Filler.wav", }},
	{ IDR_WAVE2, { "EP Progression.wav", }},
	{ IDR_WAVE3, { "EP Trap.wav", }},
	{ IDR_WAVE4, { "EP Useful.wav", }},
	{ IDR_WAVE5, { "Panel Filler 1.wav", "Panel Filler.wav", }},
	{ IDR_WAVE6, { "Panel Filler 2.wav", "Panel Filler 1.wav", "Panel Filler.wav", }},
	{ IDR_WAVE7, { "Panel Filler Epic.wav", }},
	{ IDR_WAVE8, { "Panel Progression 1.wav", "Panel Progression.wav", }},
	{ IDR_WAVE9, { "Panel Progression 2.wav", "Panel Progression 1.wav", "Panel Progression.wav", }},
	{ IDR_WAVE10, { "Panel Progression 3.wav", "Panel Progression 2.wav", "Panel Progression 1.wav", "Panel Progression.wav", }},
	{ IDR_WAVE11, { "Panel Progression Epic.wav", }},
	{ IDR_WAVE12, { "Panel Trap 1.wav", "Panel Trap.wav", }},
	{ IDR_WAVE13, { "Panel Trap 2.wav", "Panel Trap 1.wav", "Panel Trap.wav", }},
	{ IDR_WAVE14, { "Panel Trap Epic.wav", }},
	{ IDR_WAVE15, { "Panel Useful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE16, { "Panel Useful 2.wav", "Panel Useful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE17, { "Panel Useful Epic.wav", }},
	{ IDR_WAVE18, { "EP Filler 2.wav", "EP Filler 1.wav", "EP Filler.wav", }},
	{ IDR_WAVE19, { "EP Progression 2.wav", "EP Progression 1.wav", "EP Progression.wav", }},
	{ IDR_WAVE20, { "EP Trap 2.wav", "EP Trap 1.wav", "EP Trap.wav", }},
	{ IDR_WAVE21, { "EP Useful 2.wav", "EP Useful 1.wav", "EP Useful.wav", }},
	{ IDR_WAVE22, { "Panel Filler 3.wav", "Panel Filler 2.wav", "Panel Filler 1.wav", "Panel Filler.wav", }},
	{ IDR_WAVE23, { "Panel Filler 4.wav", "Panel Filler 3.wav", "Panel Filler 2.wav", "Panel Filler 1.wav", "Panel Filler.wav", }},
	{ IDR_WAVE24, { "Incoming Filler.wav", }},
	{ IDR_WAVE25, { "Incoming Progression.wav", }},
	{ IDR_WAVE26, { "Incoming Trap.wav", }},
	{ IDR_WAVE27, { "Incoming Useful.wav", }},
	{ IDR_WAVE73, { "Incoming ProgUseful.wav", }},
	{ IDR_WAVE28, { "Panel Progression 4.wav", "Panel Progression 3.wav", "Panel Progression 2.wav", "Panel Progression 1.wav", "Panel Progression.wav", }},
	{ IDR_WAVE29, { "Panel Progression 5.wav", "Panel Progression 4.wav", "Panel Progression 3.wav", "Panel Progression 2.wav", "Panel Progression 1.wav", "Panel Progression.wav", }},
	{ IDR_WAVE30, { "Victory.wav", }},
	{ IDR_WAVE69, { "Victory Understated.wav", }},
	{ IDR_WAVE31, { "Panel Trap 3.wav", "Panel Trap 2.wav", "Panel Trap 1.wav", "Panel Trap.wav", }},
	{ IDR_WAVE32, { "Panel Useful 3.wav", "Panel Useful 2.wav", "Panel Useful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE33, { "Panel Useful 4.wav", "Panel Useful 3.wav", "Panel Useful 2.wav", "Panel Useful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE34, { "Dog Trap.wav", }},
	{ IDR_WAVE35, { "Dog Filler.wav", }},
	{ IDR_WAVE36, { "Dog Progression.wav", }},
	{ IDR_WAVE37, { "Dog Useful.wav", }},
	{ IDR_WAVE70, { "Dog ProgUseful.wav", }},
	{ IDR_WAVE38, { "Pillars Filler Bmaj.wav", "Pillars Filler.wav", }},
	{ IDR_WAVE39, { "Pillars Filler EbMin.wav", "Pillars Filler.wav", }},
	{ IDR_WAVE40, { "Pillars Filler Emaj.wav", "Pillars Filler.wav", }},
	{ IDR_WAVE41, { "Pillars Progression Bmaj.wav", "Pillars Progression.wav", }},
	{ IDR_WAVE42, { "Pillars Progression EbMin.wav", "Pillars Progression.wav", }},
	{ IDR_WAVE43, { "Pillars Progression Emaj.wav", "Pillars Progression.wav", }},
	{ IDR_WAVE44, { "Pillars Trap Bmaj.wav", "Pillars Trap.wav", }},
	{ IDR_WAVE45, { "Pillars Trap EbMin.wav", "Pillars Trap.wav", }},
	{ IDR_WAVE46, { "Pillars Trap Emaj.wav", "Pillars Trap.wav", }},
	{ IDR_WAVE47, { "Pillars Useful Bmaj.wav", "Pillars Useful.wav", }},
	{ IDR_WAVE48, { "Pillars Useful EbMin.wav", "Pillars Useful.wav", }},
	{ IDR_WAVE49, { "Pillars Useful Emaj.wav", "Pillars Useful.wav", }},
	{ IDR_WAVE51, { "Bonk.wav", }},
	{ IDR_WAVE50, { "Randomized.wav", }},
	{ IDR_WAVE52, { "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE61, { "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE62, { "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE75, { "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE56, { "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE53, { "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE54, { "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE59, { "Panel Useful 5.wav", "Panel Useful 4.wav", "Panel Useful 3.wav", "Panel Useful 2.wav", "Panel Useful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE60, { "Panel Hunt Understated.wav", }},
	{ IDR_WAVE55, { "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE57, { "Panel Hunt 9.wav", "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE74, { "Panel Hunt 10.wav", "Panel Hunt 9.wav", "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE76, { "Panel Hunt 11.wav", "Panel Hunt 10.wav", "Panel Hunt 9.wav", "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE64, { "Panel Hunt 12.wav", "Panel Hunt 11.wav", "Panel Hunt 10.wav", "Panel Hunt 9.wav", "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE58, { "Panel Hunt 13.wav", "Panel Hunt 12.wav", "Panel Hunt 11.wav", "Panel Hunt 10.wav", "Panel Hunt 9.wav", "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE63, { "Panel Hunt 14.wav", "Panel Hunt 13.wav", "Panel Hunt 12.wav", "Panel Hunt 11.wav", "Panel Hunt 10.wav", "Panel Hunt 9.wav", "Panel Hunt 8.wav", "Panel Hunt 7.wav", "Panel Hunt 6.wav", "Panel Hunt 5.wav", "Panel Hunt 4.wav", "Panel Hunt 3.wav", "Panel Hunt 2.wav", "Panel Hunt 1.wav", "Panel Hunt.wav", }},
	{ IDR_WAVE65, { "Panel ProgUseful Epic.wav", }},
	{ IDR_WAVE66, { "Pillars ProgUseful Bmaj.wav", "Pillars ProgUseful.wav", }},
	{ IDR_WAVE67, { "Pillars ProgUseful EbMin.wav", "Pillars ProgUseful.wav", }},
	{ IDR_WAVE68, { "Pillars ProgUseful Emaj.wav", "Pillars ProgUseful.wav", }},
	{ IDR_WAVE72, { "EP ProgUseful 1.wav", "EP ProgUseful.wav", }},
	{ IDR_WAVE71, { "EP ProgUseful 2.wav", "EP ProgUseful 1.wav", "EP ProgUseful.wav", }},

	{ IDR_WAVE77, { "Panel ProgUseful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE78, { "Panel ProgUseful 2.wav", "Panel ProgUseful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE79, { "Panel ProgUseful 3.wav", "Panel ProgUseful 2.wav", "Panel ProgUseful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE80, { "Panel ProgUseful 4.wav", "Panel ProgUseful 3.wav", "Panel ProgUseful 2.wav", "Panel ProgUseful 1.wav", "Panel Useful.wav", }},
	{ IDR_WAVE81, { "Panel ProgUseful 5.wav", "Panel ProgUseful 4.wav", "Panel ProgUseful 3.wav", "Panel ProgUseful 2.wav", "Panel ProgUseful 1.wav", "Panel Useful.wav", }},

	{ -2, {"Challenge.wav"}},
};
